language: java
jdk:
- oraclejdk8
script: ant build
addons:
  sonarcloud:
    organization:  syd-baroya-github
    token:
      secure: d17030d8db1f869da68e9c1332e035ed2c4c8ee9
script:
  - sonar-scanner
